import re
import logging

logger = logging.getLogger("TranscriptCleaner")

# Common filler words and noise generated by ASR engines
FILLER_WORDS = [
    r"\buh\b", r"\bum\b", r"\buhh\b", r"\bumm\b", r"\bah\b", 
    r"\ber\b", r"\bhm\b", r"\bhmm\b", r"\bmhm\b", r"\bmhmm\b"
]

# Words that can be noise depending on context ("like", "you know", "so", "right", "I mean")
# We only strip them if they appear isolated or redundant, rather than stripping all "like"s.
HESITATION_PHRASES = [
    r"\byou know\b", r"\bI mean\b", r"\bso like\b", r"\blike um\b"
]

def clean_transcript(transcript: str) -> str:
    """
    Cleans a transcript by removing common filler words (um, uh)
    and formatting stuttering/repeated words.
    """
    if not transcript:
        return transcript

    cleaned = transcript
    
    # 1. Remove hesitation phrases
    for phrase in HESITATION_PHRASES:
        cleaned = re.compile(phrase, re.IGNORECASE).sub("", cleaned)
    
    # 2. Remove isolated filler words
    for filler in FILLER_WORDS:
        # Match filler word with optional punctuation, but ensure it's not part of another word
        pattern = filler + r"[,.?!]*"
        cleaned = re.compile(pattern, re.IGNORECASE).sub("", cleaned)
    
    # 3. Fix repeated words (stuttering: "the the", "I I")
    # This regex looks for a word, followed by space, followed by the exact same word
    cleaned = re.sub(r'\b(\w+)(?:\s+\1\b)+', r'\1', cleaned, flags=re.IGNORECASE)
    
    # 4. Clean up stray punctuation and extra spaces left over
    cleaned = re.sub(r'\s+([,.?!])', r'\1', cleaned) # Space before punctuation
    cleaned = re.sub(r'([,.?!])([,.?!])+', r'\1', cleaned) # Multiple punctuations ".," ".?"
    cleaned = re.sub(r'\s+', ' ', cleaned).strip() # Extra whitespace
    
    # Capitalize the first letter of each sentence
    sentences = re.split(r'([.?!]\s+)', cleaned)
    if sentences:
        formatted_sentences = []
        for s in sentences:
            if len(s) > 1 and s[-1] not in ".?! ":
                formatted_sentences.append(s[0].upper() + s[1:])
            else:
                formatted_sentences.append(s)
        cleaned = "".join(formatted_sentences)
        
    return cleaned
